### ISSUE TITLE
H5py version compatibility

### ISSUE THREAD

**Issue by heejongkim** [MPI-Dortmund/sphire_classes_autoselect#6]
Hi, 

I just wanted to report that the current Cinderella version 0.7.0 has a compatibility issue with the latest version of h5py package. (3.6.0) After searching thru similar issues, I found that 2.10.0 was happy with Cinderella 0.7.0.
I think it would be great if you can specify the compatible h5py version(s) in the requirement/dependencies.

Thanks for sharing such great software with the community.

**Comment by thorstenwagner** [comment]
Sorry, I totally forgot this issue. I changed the `setup.py` that is uses the correct h5py version.

Thanks for reporting!

Best,
Thorsten
